version: 2
jobs:
  build:
    working_directory: /tmp/favaloro
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Deploying Favaloro.
          command: echo Deploying Favaloro.
      - run:
          name: Installing dependencies.
          command: sudo pip install awscli
      - deploy:
          name: Deploy to S3 if branch is Master.
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync /tmp/favaloro/website s3://favalorodecorazon/ --delete
            fi